### ISSUE TITLE
The last window should be placed at the top [Frontend]

### ISSUE THREAD

**Issue by princeibs** [sivicstudio/starkludo#16] opened 2024-08-21 22:59 UTC
If a user opens the account window first, then opens the leaderboard window next, currently the account window will still be at the top. Your task is to bring the last opened window to the top (in this case, the account window should be stacked on top leaderboard window)

<img width="857" alt="image" src="https://github.com/user-attachments/assets/bb01e545-c430-44da-9218-85da69de9059">

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by Gift-Naomi** [comment] 2024-08-21 23:00
Can

**Comment by od-hunter** [comment] 2024-08-21 23:00
H

**Comment by thesledge04** [comment] 2024-08-21 23:00
hi

**Comment by petersdt** [comment] 2024-08-21 23:03
@princeibs

**Comment by NueloSE** [comment] 2024-08-21 23:03
@princeibs can i work on this

**Comment by martinvibes** [comment] 2024-08-21 23:21
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a frontend dev and i have skills in react, typescript, next.js, tailwind, sass, boostrap etc. i would love to work on this i i'm giving the oppotunity

### How I plan on tackling this issue
Track Window Openings:

Implement a mechanism to track the order in which windows are opened. This could be a simple array or stack data structure.
Each time a window is opened, push it onto the stack.
Adjust Window Z-Index:

When a window is opened, determine its position in the stack.
Assign a higher Z-index value to the window at the top of the stack. This will ensure it is displayed on top of other windows.
When a window is closed, remove it from the stack.
Implementation Steps:

Create a Stack Data Structure: Use an array or a dedicated stack implementation to store the order of opened windows.
Track Window Openings: When a window is opened, push its reference onto the stack.
Update Z-Index:
When a window is opened, get its index in the stack.
Assign a Z-index value based on its position (e.g., higher index for top windows).
Apply the Z-index value to the window's CSS or DOM element.
Handle Window Closing: When a window is closed, remove its reference from the stack.
Additional Considerations:

Window Focus: Ensure that the window brought to the top also receives focus, so the user can interact with it immediately.
Performance: For large numbers of windows, consider optimizing the Z-index calculations to avoid performance bottlenecks.
User Experience: Test the implementation to ensure it provides a smooth and intuitive user experience.

**Comment by CollinsC1O** [comment] 2024-08-21 23:27
Hi @princeibs I will really love to work on this

**Comment by Supa-mega** [comment] 2024-08-22 00:11
hi @princeibs will like to hop on this please

**Comment by melnikga** [comment] 2024-08-22 06:58
Hi, can I take this?
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by Otaiki1** [comment] 2024-08-22 08:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer with 3 years experience building web applications

### How I plan on tackling this issue
I would create an array ( or context) to track the order in which the windows are opened and then use this in displaying the order of the windows

**Comment by CollinsC1O** [comment] 2024-08-22 08:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a fontend and also blockchain developer

### How I plan on tackling this issue
To ensure the last window is placed at the top I will do the following:

Track Window Order: Maintain a list or stack of open windows.

Update on Focus: Whenever a window gains focus or is activated, move it to the top of the list.

Reposition Windows: Use the window management API or system calls to bring the most recently focused window to the front, ensuring it appears at the top of the z-order.

Handle Window Closure: Remove closed windows from the list and adjust the z-order accordingly.

This approach keeps the last interacted-with window on top, providing a clear user experience.

**Comment by martinvibes** [comment] 2024-08-22 08:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a frontend dev and i have skills in react, typescript, next.js, tailwind, sass, boostrap etc. i would love to work on this i i'm giving the oppotunity

### How I plan on tackling this issue
Track Window Openings:

Implement a mechanism to track the order in which windows are opened. This could be a simple array or stack data structure.
Each time a window is opened, push it onto the stack.
Adjust Window Z-Index:

When a window is opened, determine its position in the stack.
Assign a higher Z-index value to the window at the top of the stack. This will ensure it is displayed on top of other windows.
When a window is closed, remove it from the stack.
Implementation Steps:

Create a Stack Data Structure: Use an array or a dedicated stack implementation to store the order of opened windows.
Track Window Openings: When a window is opened, push its reference onto the stack.
Update Z-Index:
When a window is opened, get its index in the stack.
Assign a Z-index value based on its position (e.g., higher index for top windows).
Apply the Z-index value to the window's CSS or DOM element.
Handle Window Closing: When a window is closed, remove its reference from the stack.
Additional Considerations:

Window Focus: Ensure that the window brought to the top also receives focus, so the user can interact with it immediately.
Performance: For large numbers of windows, consider optimizing the Z-index calculations to avoid performance bottlenecks.
User Experience: Test the implementation to ensure it provides a smooth and intuitive user experience.

**Comment by ScottyDavies** [comment] 2024-08-22 08:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am front end developer with 4 years experience, 
i have worked on similar projects in the past. 
this will be my first time contributing and i am ready to work.

### How I plan on tackling this issue
Understand the Requirement: Ensure the last opened window is brought to the top.
Key Elements: Windows, tracking last opened window, updating z-index.
Solution Design:
HTML: Create windows with unique IDs
CSS: Style windows, set initial z-index
JS: Add click event listeners to windows
Remove "active" class from previous window
Set current window as active
Add "active" class to increase z-index
Implement: Code the HTML, CSS, and JS solution.
Test and Refine: Thoroughly test the implementation.
Document and Review: Review the approach and code.

**Comment by blessingbytes** [comment] 2024-08-22 08:45
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a frontend dev and i will like to participate

### How I plan on tackling this issue
Track Window States: Maintain a list or stack that keeps track of the order in which windows are opened.

Open or Focus Event: When a window is opened or focused, remove it from its current position in the list (if it exists) and then push it to the top of the list.

Reorder Windows: Adjust the window z-index or stacking order based on the updated list, ensuring the most recently opened window appears on top.

Redraw or Refresh: Trigger a UI update to reflect the new order, making the last opened window appear at the top.

Test: Ensure that the logic works by opening and focusing different windows in various orders to verify that the last interacted window is always on top.

**Comment by Benjtalkshow** [comment] 2024-08-22 08:59
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi @princeibs

I’m available to work on the "The last window should be placed at the top #16" issue. My name is Benjamin, and I have extensive experience building gamified TypeScript projects, specializing in Next.js, TypeScript, and frontend development. I’ve contributed to various projects, including those on OnlyDust, where I tackled complex UI and component challenges.

## Understanding the Issue

Currently, when multiple windows are opened, the first opened window remains on top, which can hinder user experience. For example, if a user opens the account window first and then opens the leaderboard window, the account window stays on top, covering the leaderboard window.


### How I plan on tackling this issue
### Dynamic Window Management

- **Implement Functionality:** I will implement functionality that automatically brings the last opened window to the top of the stack.
- **Focus Handling:** I will ensure that when a new window is opened, it gains focus and is displayed above any other open windows.

### Testing and Validation

- **Thorough Testing:** I will thoroughly test the window management system to ensure that the last opened window always appears on top, regardless of the order in which windows are opened.
- **Validation Across Devices:** I will validate the solution across different screen sizes and devices to ensure consistent behavior.

By applying these changes, I aim to improve the user experience by ensuring that the most recently opened window is always visible and easily accessible.

**Comment by josephchimebuka** [comment] 2024-08-22 09:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, including https://mattedsgn.vercel.app/ and https://metacrypt.vercel.app/ showcasing my expertise in React, Next.js, and blockchain technologies. I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

This is my first time on this repo I would love to contribute to it

### How I plan on tackling this issue
To solve this, I will ensure that when a user opens a new window, it is brought to the top, making it the active window above any others, including the account windo

**Comment by melnikga** [comment] 2024-08-22 10:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi, I am a frontend developer, I have participated in all ODHacks since the second one, I would be very pleased to work on your project.

### How I plan on tackling this issue
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by thesledge04** [comment] 2024-08-22 10:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a solid background in front-end development, with experience in creating and managing dynamic user interfaces. In previous projects, I’ve dealt with similar challenges where managing the z-index and visibility of overlapping UI components was crucial to maintaining a smooth user experience.

Specifically, I’ve worked with JavaScript and various front-end frameworks like React to handle window stacking and focus management. I’ve implemented solutions that automatically bring the most recently interacted with or opened component to the foreground, ensuring that the user’s focus is always where it needs to be. My understanding of DOM manipulation, event handling, and state management allows me to effectively address this problem, ensuring that the user interface behaves intuitively and consistently.

### How I plan on tackling this issue
1. Identify the Windows and Their Hierarchy:
First, I’d identify all the windows or components involved (e.g., Account window, Leaderboard window).
Ensure that each window has a way to manage its stacking order, typically using CSS z-index for web applications.
2. Track the Active Window:
Implement a system to track which window was opened last. This could be done using a variable that stores the reference or ID of the currently active (most recently opened) window.
3. Update the Z-Index Dynamically:
When a new window is opened, dynamically adjust the z-index of that window to be higher than any other currently open windows. This ensures that the new window appears on top.
For example, increment the z-index of the newly opened window to make it the topmost.
4. Handle Window Events:
Attach event listeners to the windows so that every time a window is opened or focused, it triggers an update to its z-index.
This ensures that even if a window is revisited or clicked again, it moves to the top.
5. Considerations for Multiple Windows:
If there are multiple windows open, I’d implement a system to either reset or incrementally adjust the z-index values to avoid conflicts or unnecessary stacking height.
6. Implement and Test:
After implementing the logic, I’d thoroughly test it by opening and interacting with multiple windows to ensure the correct one is always brought to the top.
I’d also test edge cases, such as rapidly switching between windows or reopening already open windows.
Example in Pseudocode:
javascript
Copy code
let zIndexCounter = 1000; // Starting z-index value

function openWindow(windowId) {
    let windowElement = document.getElementById(windowId);
    zIndexCounter++;
    windowElement.style.zIndex = zIndexCounter;
    windowElement.style.display = "block"; // Or bring it into focus
}

function focusWindow(windowId) {
    let windowElement = document.getElementById(windowId);
    zIndexCounter++;
    windowElement.style.zIndex = zIndexCounter;
}

// Example: Opening the Account window
openWindow("accountWindow");

// Example: Opening the Leaderboard window
openWindow("leaderboardWindow");

// When clicking on a window to bring it to the top
focusWindow("accountWindow");

**Comment by ShantelPeters** [comment] 2024-08-22 11:24
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i am a blockchain developer with experience in html,css,javascript ,typescript ,solidarity and cario

### How I plan on tackling this issue
You're describing a common user interface (UI) behavior for managing multiple windows or tabs. Here's how you might approach this problem, along with the reasoning behind each step:

**1. Track Window Order:**

* **Data Structure:** You'll need a way to store the order in which windows are opened. A simple approach is to use an array. For example:
    ```javascript
    let windowOrder = []; 
    ```

* **Adding Windows:**  Whenever a user opens a window, add its identifier (e.g., "accountWindow", "leaderboardWindow") to the end of the `windowOrder` array.

**2. Update Window Visibility:**

* **UI Framework:** The specific implementation will depend on your UI framework (React, Angular, Vue, etc.). 
* **DOM Manipulation:** If you're not using a framework, you'll need to manipulate the DOM (Document Object Model) to change the stacking order of your windows. This typically involves using CSS `z-index` or directly repositioning elements in the DOM.

**3.  Visual Ordering:**

* **`z-index`:** The most common approach is to use CSS `z-index`. Higher `z-index` values mean an element is placed on top of others. You can dynamically update the `z-index` of your windows based on their position in the `windowOrder` array.
* **DOM Reordering:**  You could also directly reorder the elements in the DOM. This involves using JavaScript methods like `appendChild()` or `insertBefore()` to move window elements around.

**Example (Simplified JavaScript):**

```javascript
let windowOrder = [];

function openWindow(windowId) {
  // Add window to the order
  windowOrder.push(windowId); 

  // Update window visibility (this is where you'd implement DOM manipulation)
  updateWindowVisibility();
}

function updateWindowVisibility() {
  // Example using z-index (adapt to your UI)
  windowOrder.forEach((windowId, index) => {
    document.getElementById(windowId).style.zIndex = index + 1; // Higher index = on top
  });
}

// Example usage
openWindow("accountWindow");
openWindow("leaderboardWindow"); // Now leaderboardWindow is on top
```

**Important Considerations:**

* **UI Framework:** If you're using a UI framework, it likely has built-in mechanisms for managing modal windows or tabs. These frameworks often handle the ordering and visibility automatically.
* **Performance:** If you have a large number of windows, be mindful of performance. Frequent DOM manipulations can impact performance, so consider optimizing your code.
* **User Experience:**  Think about how this behavior will impact the user experience. Make sure the window ordering is intuitive and doesn't create confusion.

**Comment by diegoTech14** [comment] 2024-08-22 11:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm Diego Duarte Fernández from Costa Rica and Dojo Coding member this is my OnlyDust profile: https://app.onlydust.com/u/diegoTech14, I would love to help with this issue. 

I have a solid background design, building and managing dynamic user interfaces, I've working with technologies like JS Vanilla, React and even Angular, of course I have experience working with CSS3. My grasp of DOM manipulation, event handling, and state management enables me to effectively tackle this problem, ensuring that the user interface operates in an intuitive and consistent manner.

### How I plan on tackling this issue
1. Analyzing the hierarchical order of the windows: This allows me to understand how it works.

2. Getting the last opened window ID: We need to know the last opened window ID, so for this I'll store that value to refer latter

3. Showing the last opened window: The easy way is to set the higher z-index value to the last opened window this way this could satisfy the requeriment

```
document.getElementById(windowId).style.zIndex = zIndexValue++;

```

4. Reseting the z-index value: If I close all the windows the z-index value will be reset
to start again with the expected behavior

5. Testing: I will ensure that the behavior is correct to the requirement interacting with many windows, closing them, reopen them and any necessary way to test it

Thanks for the consideration.

Best regards, 

Diego Duarte Fernández

**Comment by ibsule** [comment] 2024-09-03 09:09
Hi @Otaiki1, any progress on this?

**Comment by Otaiki1** [comment] 2024-09-05 11:04
Hi @princeibs , i would send in a draft PR now

**Comment by Otaiki1** [comment] 2024-09-09 09:32
Hi @princeibs , Apologies for the delay , i have made a pr [here](https://github.com/sivicstudio/starkludo/pull/65).

**Closed** 2024-09-13 04:03 UTC
Labels: good first issue, ODHack7, frontend
