### ISSUE TITLE
Add test for `get_address_from_username()` function 

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#135] opened 2024-12-17 09:37 UTC
- The function is located in the `game_actions.cairo` file
- The test should be located in the `test_game.cairo` file

**Comment by ShantelPeters** [comment] 2024-12-17 09:44
Hi @princeibs can I please be assigned to this issue

**Comment by Thibrac** [comment] 2024-12-17 10:13
I'm level 8 on node guardian and I've just finished the ecole 42 common core. I'm looking to progress and solving this issue would help me get even more involved in the ecosystem :)

**Comment by vestor-dev** [comment] 2024-12-17 10:25
May I handle this issue?
i'm a blockchain dev and would love to work on this issue 
kindly assign :)

**Comment by anonfedora** [comment] 2024-12-17 10:28
Can I be assigned to this?
I'm a fullstack Blockchain developer, proficient in Cairo, Rust, testing.

**Comment by Yunusabdul38** [comment] 2024-12-17 10:34
Gm, I'm a blockchain developer
I would like to handle this issue,
my steps 
I will locate the test in the "game_actions.cairo" file and write the function test in test_game.cairo file,  will implement the test to make sure all the assert passed and the test also passes without an error
I am confident that I can handle this
ETA < 24h

**Comment by emarc99** [comment] 2024-12-17 11:07
Let me handle this issue! This is quite straightforward, I have written tests in cairo and rust. ETA 1 day.

**Comment by FrankiePower** [comment] 2024-12-17 11:11
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the game_actions.cairo file to understand the function that needs to be tested.

Write comprehensive unit tests in the test_game.cairo file to ensure the function works as expected.

Ensure the test cases cover all edge cases, including valid and invalid inputs, and verify that the function behaves as intended.

Test that the function returns the correct outputs, and edge cases like boundary values are handled correctly.

ET: 1 day

**Comment by Jagadeeshftw** [comment] 2024-12-17 12:23
Hello @princeibs,

I’d be happy to work on this issue as well! With strong experience in developing secure and efficient smart contracts using Cairo and testing them on StarkNet, I can implement a thorough and high-quality test for the get_address_from_username() function in the test_game.cairo file.

If approved, I’ll ensure to deliver a well-structured and robust PR within 12-24 hours. Let me know if I can proceed!

Thank you, and I’m eager to contribute.

**Comment by 1nonlypiece** [comment] 2024-12-17 12:41
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment] 2024-12-17 12:48
I'd love to work on this!
ETA: 1 day

**Comment by OJDIT** [comment] 2024-12-17 13:32
Is it okay if I take this?

**Comment by ryzen-xp** [comment] 2024-12-17 13:51
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment] 2024-12-17 14:13
Let me handle this issue!

**Comment by GideonBature** [comment] 2024-12-17 14:37
I'd love to work on this!

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I will love to work on this issue, writing the function in the smart contract and integration test for the function in the smart contract. If I am assigned, I will send my first PR within 24 hours.

Thank you!

**Comment by obacollins-lab** [comment] 2024-12-17 15:24
Mind if I take this issue?

**Comment by Xaxxoo** [comment] 2024-12-17 16:26
Hi, may I take up on this?

**Closed as completed** 2024-12-27 10:55 UTC
Labels: good first issue, onchain, ODHack11
