### ISSUE TITLE
Pieces should be below window

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#22] opened 2024-08-23 20:43 UTC
When the windows are moved over the board, they should appear above the Ludo pieces on the board and not below. Currently the pieces appear above the windows. This is a problem related to the `z-index` of the Ludo pieces or the windows.
![image](https://github.com/user-attachments/assets/70afee15-9af3-487b-94c8-16da9d6a76e9)

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by 0xOlivanode** [comment] 2024-08-23 20:44
iii

**Comment by Jemiiah** [comment] 2024-08-23 20:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
M

**Comment by 0xOlivanode** [comment] 2024-08-23 20:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend and cairo dev

### How I plan on tackling this issue
I want to jump on this isuue

**Comment by Naomi-Gift** [comment] 2024-08-23 20:50
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer

### How I plan on tackling this issue


1. Identify the CSS class or ID of the windows and give them a higher `z-index` value than the Ludo pieces.
2. For example, set `z-index: 10;` on the windows and `z-index: 5;` on the Ludo pieces.
3. Ensure the elements are positioned (using `position: relative;`, `absolute;`, or `fixed;`) for `z-index` to take effect.

**Comment by Solomonsolomonsolomon** [comment] 2024-08-23 20:54
I will love to work on this issue @princeibs

**Comment by CollinsC1O** [comment] 2024-08-23 20:56
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a frontend and a blockchain developer and I will love to work on this

### How I plan on tackling this issue
To ensure pieces are displayed below the window, I did follow these steps:

    Adjust Layout: Modify the CSS or layout properties to position the pieces below the viewport or main content area.

    Use Overflow: Set the overflow property of the container to handle content that extends beyond the visible window.

    Positioning: Apply appropriate position and z-index properties to make sure pieces appear below other elements if necessary.

    Test Across Devices: Verify the positioning on different screen sizes and resolutions to ensure consistent display below the window.

**Comment by SoarinSkySagar** [comment] 2024-08-23 21:25
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full stack Web3 developer with over a year of experience in creating dapps. Prior to that, I have been working as a full stack developer. My tech stacks include Next.js, React.js, Express.js and typescript. My speciality is creating beautiful frontends and complex backend designs. I love contributing to open source repositories where I can learn new stuff and contribute to the development of an organisation.

### How I plan on tackling this issue
Since it has been mentioned that the problem is related to the z-index of the ludo pieces or the windows, there can be three approaches here in my opinion:
1. Decrease the z-index of the pieces
2. Decrease the z-index of the pieces when the window is open
3. Increase the z-index of the the window

In my opinion, the third approach should be the fastest and best approach, but I am all down for working on a different approach and even explore other methods if required. 

Also, if I am assigned, I will:
1. Make sure the code is clean, readable and error-free
2. Comments added wherever required
3. Documentation updated wherever required
4. Thoroughly tested for any errors before the PR

I would really like to work and resolve this issue, so please assign me @princeibs

**Comment by PabloVillaplana** [comment] 2024-08-23 22:04
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, specializing in building robust and scalable web applications. My journey has equipped me with a deep understanding of both front-end and back-end technologies, enabling me to deliver comprehensive solutions. I am incredibly passionate about emerging technologies, and I’m particularly excited to contribute to Web 3 projects. This opportunity allows me to further my growth as an Open Source Contributor, helping to shape the future of decentralized web applications. I am eager to leverage my skills and experience to make meaningful contributions to the community while continuing to learn and evolve in this dynamic field.

### How I plan on tackling this issue


Determine the CSS class or ID associated with the windows and assign them a higher z-index value compared to the Ludo pieces.

For instance, you might apply z-index: 10; to the windows and z-index: 5; to the Ludo pieces.
Ensure that the relevant elements have a positioning context applied (such as position: relative;, absolute;, or fixed;) to allow the z-index values to function correctly.

**Comment by od-hunter** [comment] 2024-08-23 22:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi, please can I work on this? I am a blockchain developer with experience in html, css, react, JavaScript, typescript, solidity and Cairo.

### How I plan on tackling this issue
To solve this I'd:
1. I'll set a lower z-index for the Ludo pieces (e.g., z-index: 1).
2. I'll now set a higher z-index for the windows (e.g., z-index: 10).
3. Lastly, I'll ensure both elements have a position property (e.g., relative or absolute).

Please assign this issue to me.

**Comment by Benjtalkshow** [comment] 2024-08-23 22:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi @princeibs,

I'm Benjamin, and I have 3 years of experience in Frontend JavaScript development, including handling complex UI issues. I’d be glad to help resolve the z-index issue with the Ludo pieces and windows.

### How I plan on tackling this issue
- I will inspect the current z-index settings for both the Ludo pieces and the windows.
- I will determine which elements are causing the pieces to appear above the windows.
- I will reconfigure the z-index values so that the windows have a higher z-index than the Ludo pieces.
- I will ensure that the Ludo pieces remain properly layered under normal gameplay but correctly appear below windows when they overlap.
- I will test the updated z-index settings across different scenarios, including moving windows over the board and interacting with Ludo pieces.

**Comment by addegbenga** [comment] 2024-08-24 00:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend engineer with over 5 years experience in software development

### How I plan on tackling this issue
I will look for the styling ot the board and make sure every component poping over the board has a higher z-index

**Comment by JoelVR17** [comment] 2024-08-24 02:10
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a Full Stack Web Developer with a solid background in front-end and back-end development. So it will be a pleasure to contribute for the first time to this great project.
*_I'm member of Dojo Coding_*

### How I plan on tackling this issue
1. **Understand the Current Structure:**
   - I would start by examining the DOM structure and CSS styles of both the Ludo pieces and the windows. This involves checking the stacking context, how z-index is applied, and whether any parent elements have properties that create new stacking contexts (like `position: relative`, `position: absolute`, or `position: fixed`).

2. **Identify the Source of the Issue:**
   - I would inspect the elements in the browser's developer tools to see how z-index values are applied and whether the windows or Ludo pieces are inside any elements that could be affecting their stacking context.
   - It's essential to determine if the z-index of the Ludo pieces is higher than that of the windows or if there are other properties creating unintended stacking contexts.

3. **Adjust z-index and Stacking Contexts:**
   - Once the issue is identified, I would adjust the z-index values to ensure that the windows appear above the Ludo pieces. If necessary, I would modify the CSS to create a stacking context for the windows that allows them to appear on top.
   - For example, if the Ludo pieces have a higher z-index or are inside an element with a stacking context, I might update the window elements like this:
     ```css
     .window {
       position: absolute;
       z-index: 1000; /* Ensures windows are above Ludo pieces */
     }

     .ludo-piece {
       position: relative;
       z-index: 10; /* Lower z-index for pieces */
     }
     ```
   - If the windows are currently being hidden by another stacking context, I would ensure that they are placed in the correct context or modify their parent elements to avoid this issue.

4. **Testing and Validation:**
   - After making the adjustments, I would thoroughly test the application to ensure that the windows now correctly appear above the Ludo pieces, regardless of their position on the board.
   - I would test across different browsers and screen sizes to ensure consistency in how the z-index is applied.

5. **Collaboration and Communication:**
   - If I encounter any difficulties or need further clarification, I would reach out to the project leads through the StarkLudo contributors channel on Telegram. This allows me to ensure that my solution aligns with the project’s goals and standards.

6. **Documentation:**
   - Finally, I would document the changes made to the z-index and stacking contexts. This documentation would include explanations of why the changes were necessary and how they solve the problem, ensuring that future developers understand the rationale behind these adjustments.

**Comment by ShantelPeters** [comment] 2024-08-24 05:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a frontend dev and  i will love to work on this please
i would deliver on the asap

### How I plan on tackling this issue
    Identify Elements: Determine the CSS classes or IDs for the Ludo pieces and the windows.

    Adjust z-Index: Update the z-index values in the CSS to ensure that windows appear above the Ludo pieces. Set a higher z-index for the windows compared to the Ludo pieces.

    Verify Changes: Test by moving the windows over the board to confirm that they appear above the Ludo pieces.

    Seek Help if Needed: If you have questions or need further clarification, join the StarkLudo contributors channel on Telegram for assistance.

**Closed as completed** 2024-09-01 13:12 UTC
Labels: good first issue, ODHack7, frontend
