### ISSUE TITLE
Fix lint issue with client

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#125] opened 2024-12-13 08:53 UTC
## Description
- Fix issue causing the client not to pass the CI checks 
![image](https://github.com/user-attachments/assets/11d20f17-b8bb-4cb8-97b1-06d8296e63e8)

## ETA
This issue is expected to be completed within 1 business day or being assigned. Failure to create a pull request or draft pull request will lead to the contributor being unassigned

**Comment by sonkiee** [comment] 2024-12-13 09:06
Hello, can I take this task

**Comment by Jagadeeshftw** [comment] 2024-12-13 09:18
May I pick this up?

**Comment by emarc99** [comment] 2024-12-13 09:22
Please let me do this. ETA - 1 day. I have Cairo experience [dev set up already](https://emarc.hashnode.dev/starknet-development-with-docker-a-streamlined-setup-for-cairo-builders) and typescript [contributed here](https://github.com/Crypto-Jaguars/Revolutionary_Farmers/pull/29) as well.

**Comment by Pvsaint** [comment] 2024-12-13 09:34
Can I take this issue? I'm a front-end and smart contract developer proficient in react, next js, solidity and cairo

**Comment by Luluameh** [comment] 2024-12-13 09:37
I’m interested in this one.
Eta: within 8hrs

**Comment by FrankiePower** [comment] 2024-12-13 09:47
Let me try this one!

**Comment by FrankiePower** [comment] 2024-12-13 09:47
Request to Fix Issue Causing CI Check Failures

Hello, team!
I want to take on the task of resolving the issue preventing the client from passing the Continuous Integration (CI) checks.

I am Super Franky, a frontend developer and recent graduate from web3bridge Africa, Africa's premier and biggest blockhain developer community. Below is the plan of action for addressing the issue:

Plan of Action:

1. Identifying the Root Cause:
   - I will review the CI logs to identify the specific errors or issues causing the failure.

2. Fixing the Issue:
   - Based on the identified issue, I will take the necessary steps to fix it. This may involve:
     - Code Refactoring: If the issue is related to the codebase (e.g., syntax or formatting issues), I will ensure the code adheres to the project's coding standards.
     - Dependencies: If the issue is related to outdated or incorrect dependencies, I will update or correct the dependencies to ensure compatibility.
     - Build Issues: If the issue is related to the build process, I will review and correct the configuration files (e.g., `webpack`, `tsconfig.json`, or `package.json`).

I look forward to contributing to this project

Thank you!

Super Franky

**Comment by DioChuks** [comment] 2024-12-13 09:49
May I handle this issue?

**Comment by kcmikee** [comment] 2024-12-13 10:02
Hi, i'm Mike,  I have experience in resolving issues like this, can I take this issue?

**Comment by tosinmoses384** [comment] 2024-12-13 10:27
I will address this issues in the following ways:

1. Check logs and error
2. Check Cairo code issues
3. Typescript Code issue
4. Check Dependencies
5. Confirm by running unit test

**Comment by Superfly101** [comment] 2024-12-13 10:34
Can I be assigned to this? I am verify familiar with GitHub actions and the steps I would take to tackle this issue would include:

1) To first see the details of the check failing and review the logs to identify the cause of the failure.
2) Make the necessary changes to resolve the error

ETA: 1 day (max)

**Comment by 3th-Enjay** [comment] 2024-12-13 11:19
Would love to tackle this!

**Comment by Dorcas18** [comment] 2024-12-13 11:55
I'd be happy to do this.

**Comment by dadadave80** [comment] 2024-12-13 12:10
May I take this issue on?

**Comment by Jayrodri088** [comment] 2024-12-13 13:21
Hi, I'm John Asogwa, and I will love to work on this issue.
I'm an experienced developer with expertise in debugging CI/CD pipelines and resolving build and test issues.

I estimate this issue can be resolved within 1 business day.

Steps to Resolve
Reproduce the Issue Locally

Run the CI pipeline commands locally to identify the root cause of the failure.
Check for issues in dependencies, TypeScript compilation, or linting.
Inspect and Fix Errors

Resolve any missing dependencies by updating the pnpm-lock.yaml file or adding them to package.json.
Fix TypeScript errors in the source code and ensure all modules and imports are configured correctly.
Address linting and formatting errors to match project standards.
Check CI Environment

Review the CI configuration file for environment mismatches or missing setup steps.
Ensure Node.js and pnpm versions are aligned between local and CI environments.
Validate the Fix

Test the build process locally after applying fixes.
Push the changes and verify the CI pipeline completes successfully.
Final Steps
Once the fix is verified, I will:

Commit the changes to a branch named fix-client-ci.
Open a pull request with a detailed explanation of the issue and resolution.
I’m confident this will resolve the issue, ensuring a smooth CI pipeline for StarkLudo.

**Comment by Joewizy** [comment] 2024-12-13 13:25
Let me handle this issue! I can finish this task today

**Comment by Supa-mega** [comment] 2024-12-13 14:33
Is it okay if I take this? first time contributor ETA 24 hours

**Closed as completed** 2024-12-16 16:40 UTC
Labels: good first issue, frontend, ODHack11
