### ISSUE TITLE
Add banner to game

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#25] opened 2024-08-23 21:33 UTC
Add a banner to the buttom of the game with the content: "Powered by Starknet and Dojo Engine".
You can get inspiration from here: 
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/19c0d38a-bdeb-4962-bc3d-915124aca4e4">

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by Naomi-Gift** [comment] 2024-08-23 21:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer

### How I plan on tackling this issue
I will Add a div with the text "Powered by Starknet and Dojo Engine" at the bottom of your HTML. Style it with position: fixed; bottom: 0; width: 100%; and appropriate background and text colors. Ensure it has a high z-index to stay above other content.

**Comment by MariangelaNM** [comment] 2024-08-23 21:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello! I'm Mariángela, a passionate Software Engineer based in Costa Rica. I'm part of  Dojo Coding community. With over four years of experience as a full-stack developer, I have honed my skills in both backend and frontend development, with a particular focus and specialization in frontend technologies.

I am always eager to explore new challenges and expand my expertise, especially in innovative projects like this hackathon. My goal is to make impactful contributions that leverage my deep understanding of the development process, from concept to deployment, while continuously learning and growing within the dynamic tech landscape.

### How I plan on tackling this issue
1. **Create a Banner Element:**
   - Add an element at the bottom of the game layout that will contain the banner.

2. **Position the Banner:**
   - Ensure that the banner is positioned at the bottom of the game screen, fixed in place so it remains visible at all times.

3. **Style the Banner:**
   - Style the banner to match the game’s theme. Use appropriate background color, text color, and font size to ensure readability without distracting from the gameplay.

4. **Include the Banner in All Game Screens:**
   - Make sure the banner is present on all relevant screens or pages of the game, so it’s consistently displayed.

5. **Test the Banner:**
   - Test the banner’s appearance on various devices and screen sizes to confirm that it’s displayed correctly and doesn’t interfere with gameplay.

**Comment by Solomonsolomonsolomon** [comment] 2024-08-23 21:47
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
MERN stack developer with 3+ years experience

### How I plan on tackling this issue
i'll create a footer with the words Powered by Starknet and Dojo Engine at the bottom of the markup,ensure its fixed in place at the bottom and styled appropriately

**Comment by ShantelPeters** [comment] 2024-08-23 21:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a frontend dev

**Comment by PabloVillaplana** [comment] 2024-08-23 21:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor.

### How I plan on tackling this issue
This won't take long to resolve, the longest time it would take would be to set up the project and get it working properly locally.


Add a Banner Element: Incorporate an element at the bottom of the game layout dedicated to the banner.

Ensure the banner is anchored at the bottom of the game screen, keeping it fixed and always visible.

Customize the banner’s appearance to align with the game’s theme. Choose background color, text color, and font size carefully to maintain readability without disrupting the gameplay experience.

Ensure the banner is consistently displayed across all relevant screens or pages of the game.

**Comment by GoSTEAN** [comment] 2024-08-23 22:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a frontend dev and i would love to do this issue

### How I plan on tackling this issue
Design the Banner:

### Create a visual mockup with the text "Powered by Starknet and Dojo Engine."
Choose colors and fonts that match your game's style.
Save the banner as an image file (e.g., PNG or JPEG).
Integrate the Banner:

### Add the banner image to your game project’s assets folder.
Update your game code or UI to display the banner at the bottom of the screen:
For Web Games: Use HTML and CSS.
For Unity: Add an Image UI element to a Canvas.
For Unreal Engine: Use a UMG Widget Blueprint.
Test the Banner:

### Check the banner’s visibility and position in different screen resolutions and aspect ratios.
Adjust the design or placement if necessary.
Deploy and Update:

Build and deploy the updated game version.
Update documentation or release notes if needed.

**Comment by khayss** [comment] 2024-08-23 22:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a fullstack web3 developer. I'm detail oriented and strive for achieving optimal results. I have worked on several frontend projects. I have excellent knowledge of typescript and building frontends with it.

### How I plan on tackling this issue
- I will  create and style a custom UI banner component,
- I will add the Starknet and Dojo logo.
- I will ensure the component is responsive across various screen breakpoints.
- I will ensure the component styling is in sync with the project styling guideline.

**Comment by Benjtalkshow** [comment] 2024-08-23 22:15
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi @princeibs,

I'm Benjamin, and I have 3 years of experience in Frontend JavaScript development. I’m skilled in creating both 2D and 3D games using JavaScript. I can handle adding a banner to the bottom of the game.

### How I plan on tackling this issue
- Identify the right place: Find the appropriate location in the game’s layout where the banner should be added.
- Create the banner element: Design a banner using tailwindcss and vite or the game’s existing styling system, ensuring it fits well with the rest of the game’s design.
- Add the content: Insert the text "Powered by Starknet and Dojo Engine" into the banner.
- Position the banner: Use tailwind or the game’s positioning methods to place the banner at the bottom of the screen.
- Test and adjust: Verify that the banner appears correctly across different screen sizes and make any necessary adjustments.

**Comment by MullerTheScientist** [comment] 2024-08-23 22:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full-stack developer with experience in languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
I will Ensure the banner is visually appealing and non-intrusive.
Use a consistent font and color scheme with the game's branding.
Test the banner's positioning and visibility on different devices and browsers.

**Comment by ScottyDavies** [comment] 2024-08-23 23:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My background includes:

5+ years of experience building decentralized applications (dApps) on the Ethereum blockchain, leveraging frameworks like Truffle and Hardhat.

Deep understanding of Solidity and the Ethereum Virtual Machine (EVM), allowing me to write efficient and secure smart contracts.

Growing expertise in the Starknet ecosystem, including hands-on experience with the Cairo programming language and the Dojo Engine for building zero-knowledge-based applications.

Strong front-end development skills, particularly with React and other modern JavaScript frameworks, enabling me to seamlessly integrate the banner component into the game's user interface.

### How I plan on tackling this issue
I would approach the problem of adding a banner to the StarkLudo game, including the front-end framework, Starknet, and Dojo Engine. I would then design a reusable, responsive, and visually appealing banner component that aligns with the game's design and includes the required "Powered by Starknet and Dojo Engine" content. Optionally, I would  leverage the Starknet blockchain to enhance the banner's functionality, such as fetching and displaying dynamic data. Finally, I would thoroughly test the banner component, collaborate with the project team on the Telegram channel, and work to deploy the updated game version with the new banner

**Comment by NueloSE** [comment] 2024-08-24 01:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend develop with some years of experience with frontend technology using js, typescript and some frontend frame works.

With the above technologies i believe i would be able to contribute to the following project

**Comment by JoelVR17** [comment] 2024-08-24 02:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a Full Stack Web Developer with a solid background in front-end and back-end development. So it will be a pleasure to contribute for the first time to this great project.
*_I'm member of Dojo Coding_*

### How I plan on tackling this issue
1. **Review the Design Inspiration:**
   - First, I would check any design inspirations or guidelines provided in the issue description or other references to understand the style and positioning of the banner.
   - If no specific design inspiration link is provided, I would reach out via the StarkLudo contributors channel on Telegram for more details or proceed with a clean and professional design that matches the current game interface.

2. **Determine Banner Placement and Structure:**
   - I would determine the best way to integrate the banner into the game, ensuring that it is always visible at the bottom of the screen, regardless of the device or screen size. I would consider whether the banner should be fixed or if it should scroll with the content.

3. **Implement the Banner in Next.js:**
   - I would create a new component for the banner to ensure modularity and reusability. This component would include the content "Powered by Starknet and Dojo Engine."
   - The component could be placed in the appropriate page or layout file to ensure it appears across the game as intended.

   Example code:
   ```tsx
   // components/Banner.tsx
   import React from 'react';

   const Banner: React.FC = () => {
     return (
       <div className="fixed bottom-0 left-0 right-0 bg-gray-900 text-white text-center py-2">
         Powered by <span className="font-bold">Starknet</span> and <span className="font-bold">Dojo Engine</span>
       </div>
     );
   };

   export default Banner;

**Comment by ShantelPeters** [comment] 2024-08-24 05:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs i'm a frontend developer and i would love to work on this please

### How I plan on tackling this issue
    Add HTML Element: Place a div at the bottom of your game container to hold the banner text.

    Style the Banner:
        Position the banner to stay fixed at the bottom of the screen.
        Set the banner to cover the full width of the screen.
        Choose a dark background color with light-colored text for good contrast.
        Center the text horizontally and add padding for spacing.

    Make it Responsive: Ensure the banner adapts to different screen sizes by adjusting the font size and padding for smaller devices.

**Comment by Agbeleshe** [comment] 2024-08-24 06:58
Hello @princeibs  I can handle this. I would love to make my first contribution on this space.
i have also applied via [OnlyDust platform](https://app.onlydust.com/p/starkludo) platform.

**Background**
I am a Frontend React developer with over 3 years of hands-on experience in React, Next.js, TypeScript, and related frameworks. I’ve built numerous frontend projects with stunning designs, mastering efficient and effective ways to implement them.

**My Approach**
I would first analyze the web layout, implement an appropriate style that matches web design, and then use a reusable component to apply the banner to the necessary pages. thank you

**Comment by Agbeleshe** [comment] 2024-08-24 07:01
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Frontend React developer with 3 years of hands-on experience in React, Next.js, TypeScript, and related frameworks. I’ve built numerous frontend projects with stunning designs, mastering efficient and effective ways to implement them. I focus on creating designs that are not only visually appealing but also interactive and scalable.

### How I plan on tackling this issue
I would first analyze the web layout, select the appropriate styles to design the banner, and then use a reusable component to apply the banner to the necessary pages.

**Closed as completed** 2024-09-02 07:13 UTC
Labels: good first issue, ODHack7, frontend
