### ISSUE TITLE
Add test for `get_username_from_address()` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#134] opened 2024-12-17 09:35 UTC
- The function is located in the `game_actions.cairo` file
- The test should be located in the `test_game.cairo` file

**Comment by Thibrac** [comment] 2024-12-17 10:13
I'm level 8 on node guardian and I've just finished the ecole 42 common core. I'm looking to progress and solving this issue would help me get even more involved in the ecosystem :)

**Comment by Birdmannn** [comment] 2024-12-17 10:21
Goodmorning dev. Can I hop on this task? I have good experience in writing cairo tests, and I'm familiar with the testing tools. I'll write extensive test on this function carrying out all possible test scenarios without breaking the existing code.

ETA is 2 hours

**Comment by vestor-dev** [comment] 2024-12-17 10:25
I'd be happy to do this.
May I handle this issue?
i'm a blockchain dev and would love to work on this issue 
kindly assign :)

**Comment by anonfedora** [comment] 2024-12-17 10:28
Can I be assigned to this?
I'm a fullstack Blockchain developer, proficient in Cairo, Rust, testing.

**Comment by Yunusabdul38** [comment] 2024-12-17 10:36
Gm, I'm a blockchain developer
I would like to handle this issue,
my steps 
I will locate the test in the "game_actions.cairo" file and write the function test in test_game.cairo file,  will implement the test to make sure all the assert passed and the test also passes without an error
I am confident that I can handle this

**Comment by emarc99** [comment] 2024-12-17 11:07
I’m interested in this one.

**Comment by FrankiePower** [comment] 2024-12-17 11:11
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the game_actions.cairo file to understand the function that needs to be tested.

Write comprehensive unit tests in the test_game.cairo file to ensure the function works as expected.

Ensure the test cases cover all edge cases, including valid and invalid inputs, and verify that the function behaves as intended.

Test that the function returns the correct outputs, and edge cases like boundary values are handled correctly.

ET: 1 day

**Comment by Jagadeeshftw** [comment] 2024-12-17 12:21
Hello @princeibs,

I’d love to contribute to this issue! I have strong experience developing efficient and secure smart contracts using Cairo and working within the StarkNet ecosystem. I can implement a robust and comprehensive test for the get_username_from_address() function in the test_game.cairo file, ensuring it meets expected behaviours and edge cases.

If approved, I’ll deliver a high-quality PR within the next 12-24 hours. Let me know if you’d like me to proceed!

Thank you, and I look forward to contributing.

**Comment by 1nonlypiece** [comment] 2024-12-17 12:42
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment] 2024-12-17 12:48
Could I take on this issue?
ETA: 1 day

**Comment by OJDIT** [comment] 2024-12-17 13:32
I'd like to handle this task.

**Comment by ryzen-xp** [comment] 2024-12-17 13:52
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment] 2024-12-17 14:13
Can I work on this, please?

**Comment by GideonBature** [comment] 2024-12-17 14:38
I'd love to work on this!

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I will love to work on this issue, writing the integration test for the function in the smart contract. If I am assigned, I will send my first PR within 24 hours.

Thank you!

**Comment by obacollins-lab** [comment] 2024-12-17 15:24
May I be assigned to this?

**Comment by NueloSE** [comment] 2024-12-17 16:28
I'd like to take this issue. I have experience in writing and testing smart contracts kindly assign me .

**Closed as completed** 2024-12-23 16:00 UTC
Labels: good first issue, onchain, ODHack11
