### ISSUE TITLE
Design new Ludo boards

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#20] opened 2024-08-23 20:39 UTC
Design 2 new boards for StarkLudo on Figma. You can make research about various boards design and variation of the Ludo game. If you can come up with more than 2 boards, the extra effort will be accounted for.

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by ooochoche** [comment] 2024-08-23 20:40
@princeibs I can work on this, I am a ui designer

**Comment by Calebux** [comment] 2024-08-23 20:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I can jump on this

### How I plan on tackling this issue
Design a clean board

**Comment by CollinsC1O** [comment] 2024-08-23 20:42
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I can work on this

### How I plan on tackling this issue
To solve the issue of designing new Ludo boards, I did consider these steps:

Research and Inspiration: Explore various themes, cultural designs, and game mechanics. Look at different board games and artistic styles to gather ideas.

Concept Development: Create several design concepts with different themes (e.g., fantasy, space, historical) and variations (e.g., circular boards, multiple pathways).

Prototype Creation: Develop prototypes of the new board designs using digital tools or physical materials to test functionality and aesthetics.

User Testing: Gather feedback from players to ensure the new designs are engaging, functional, and user-friendly.

Refinement: Make necessary adjustments based on feedback and testing results, focusing on improving playability and visual appeal.

Production and Distribution: Finalize the design and work with manufacturers to produce the new boards. Develop a marketing strategy to promote the redesigned Ludo boards.

**Comment by ooochoche** [comment] 2024-08-23 20:44
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Product Designer 

### How I plan on tackling this issue
- Do some research on Ludo board designs
- Use my findings to create a design that aligns with the project idea

**Comment by SoarinSkySagar** [comment] 2024-08-23 21:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full stack Web3 developer with over a year of experience in creating dapps. Prior to that, I have been working as a full stack developer. My tech stacks include Next.js, React.js, Express.js and typescript. My speciality is creating beautiful frontends and complex backend designs. I also have experience in designing wireframes and designs on Figma, as I have been required to do so multiple times during my internships and freelance projects. I love contributing to open source repositories where I can learn new stuff and contribute to the development of an organisation. 

### How I plan on tackling this issue
Create atleast 4 beautiful and unique boards for the website. The website is dark themes so 3 out of the 4 will be dark themes boards while one will be light themes. I will keep the design and pattern of the webpage in mind to maintain the consistency of the UI for the new boards.

**Comment by Ugo-X** [comment] 2024-08-23 22:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach solving this issue in the following steps:

1. Research Phase:
   - I will investigate various Ludo board designs and variations globally.
   - Study color theories and cultural influences on game board designs.
   - Explore modern design trends in board games, particularly those with a digital twist.

2. Conceptualization:
   - Brainstorm unique themes for the new boards (e.g., futuristic, nature-inspired, abstract).
   - Sketch initial ideas, focusing on layout and distinctive features.

3. Figma Design:
   - Create at least two new board designs in Figma, ensuring they're visually appealing and functional.
   - Incorporate StarkLudo's branding elements while introducing fresh aesthetics.
   - Design additional elements like dice, pawns, and UI components to complement each board.

4. Iteration and Refinement:
   - Review designs with peers or potential users for feedback.
   - Refine designs based on feedback, ensuring clarity and visual appeal.

5. Extra Effort:
   - If time allows, design one or two additional board variations.
   - Create animations or interactive elements in Figma to showcase board features.

6. Documentation and Presentation:
   - Prepare a brief explanation for each design, highlighting unique features and inspirations.
   - Create a presentation showcasing the designs and thought process.

This approach aims to deliver creative, well-researched designs that enhance the StarkLudo gaming experience while potentially exceeding the initial requirement of two boards.

**Comment by Osatuyi** [comment] 2024-08-23 22:05
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a uiux designer with 2years experience designing Web 2 and Web 3 products (especially web 3 game ui) using the latest design technologies. I pride myself in delivering an excellent job and doing so in time.
Here's my portfolio: https://www.figma.com/proto/HcFnqYWAab3sA4ws0oL8HL

### How I plan on tackling this issue
I will make proper research on various ways the Ludo board game can be presented and design wireframes that are both clean and interesting to interact with.
I would love to be assigned this issue.

**Comment by Benjtalkshow** [comment] 2024-08-23 22:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi @princeibs,

I'm Benjamin, and I have 3 years of experience in Frontend JavaScript development, including game design and UI/UX designs. I’d love to contribute to the StarkLudo project by designing new Ludo boards and using it as an avenue to showcase my UI/UX skill. 

### How I plan on tackling this issue
- I will investigate various Ludo board designs and variations to gather ideas and inspirations and explore different themes, layouts, and color schemes to create unique and engaging boards.
- Conceptualization: Develop concepts for at least two new Ludo boards, considering different gameplay dynamics and visual styles.
- I will create detailed mockups for each board using Figma.
- Lastly, I will ensure the designs offer varied gameplay experiences and aesthetics.

**Comment by ScottyDavies** [comment] 2024-08-24 00:46
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm  frontend developer with years of experience and I want to contribute to this ecosystem, 

### How I plan on tackling this issue
I would approach the task with the following steps :

1  Research and Exploration:
I would begin by exploring various Ludo game board designs and variations. This would include analyzing the traditional Ludo board as well as investigating different interpretations and adaptations of the game.
2  Design Ideation: 
Using the information gathered from the research phase, I would start ideating on new board designs for StarkLudo. This would involve considering different themes, shapes, layouts, and overall aesthetics that could enhance the player's experience.
3  Wireframing and Mockups: 
I would create low-fidelity wireframes and mockups to explore the structure and flow of the new board designs. This would help me experiment with different ideas and refine the concepts.
4  Visual Design:
 Once the wireframes and mockups are solidified, I would focus on the visual design of the boards. This would include selecting appropriate color palettes, typography, iconography, and other visual elements to create a cohesive and visually appealing design.
5  Iterative Refinement:
 I would continuously refine the board designs, seeking feedback and incorporating user insights to ensure the final products are engaging, intuitive, and aligned with the overall branding and vision of the StarkLudo game.
6  Presentation and Documentation:
 I would prepare a comprehensive presentation or documentation to showcase the new board designs, including the design rationale, key features, and potential implementation considerations.

**Comment by JoelVR17** [comment] 2024-08-24 02:13
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a Full Stack Web Developer with a solid background in front-end and back-end development. So it will be a pleasure to contribute for the first time to this great project.
*_I'm member of Dojo Coding_*

### How I plan on tackling this issue
1. **Research and Inspiration:**
   - **Explore Existing Ludo Designs:** I would start by researching different Ludo board designs, both traditional and modern. This includes analyzing variations in board layout, color schemes, and thematic elements used in other versions of Ludo.
   - **Study Board Design Principles:** I would review principles of board game design, focusing on elements that enhance user experience and ensure clarity of gameplay.

2. **Design Exploration:**
   - **Initial Concepts:** I would create initial sketches and concepts for the new boards, experimenting with different layouts, color palettes, and visual styles. This will help identify the most promising design directions.
   - **Design Variations:** Based on the research and initial concepts, I would design at least two distinct board variations, each with unique visual and functional elements. If I come up with additional creative ideas, I will include those as extra options.

3. **Figma Design:**
   - **Create Detailed Mockups:** I would use Figma to create high-fidelity mockups of the new boards. This includes defining the layout, adding visual elements, and ensuring that the design aligns with the game's theme and mechanics.
   - **Interactive Elements:** If applicable, I would include interactive elements in the Figma design to demonstrate how the board will function in practice.

4. **Feedback and Iteration:**
   - **Seek Feedback:** I would share the designs with the StarkLudo team and other contributors to gather feedback. This will ensure that the designs meet the project’s needs and expectations.
   - **Refine Designs:** Based on the feedback, I would make necessary revisions and improvements to the designs to ensure they are polished and ready for implementation.

5. **Documentation and Delivery:**
   - **Provide Documentation:** I would document the design process, including any design choices, color codes, and layout details. This will help ensure a smooth handoff to developers or other team members.
   - **Deliver Design Files:** I would deliver the final Figma files and any related assets to the team, ensuring they are organized and easy to use.

6. **Join the StarkLudo Contributors Channel:**
   - **Engage with the Community:** If I have any questions or need further clarification, I will join the StarkLudo contributors channel on Telegram to connect with project leads and other contributors. This will help ensure that my designs align with the project’s goals and requirements.

By following this approach, I aim to create two high-quality, engaging, and innovative Ludo board designs that enhance the overall user experience for StarkLudo.

**Comment by ShantelPeters** [comment] 2024-08-24 05:17
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a ui/ux designer and would love to work on this if i'm giving the opportunity

### How I plan on tackling this issue
Research Ludo Designs: Explore various Ludo board designs and variations to gather inspiration. Look at traditional designs as well as modern takes.

Create New Boards:

    Design 1: Develop a classic or slightly modified Ludo board with distinct visual elements.
    Design 2: Experiment with a different theme or layout, such as a circular or multi-layered board.

Use Figma:

    Create the boards in Figma, ensuring they are clear, visually appealing, and functional.
    Utilize Figma's tools for precision and creativity, such as grids, shapes, and colors.

Additional Designs (Optional): If inspired, create more than two board designs to offer a variety of options.

Review and Feedback: Share your designs with others for feedback and make any necessary adjustments.

Seek Assistance: If you need more clarity, join the StarkLudo contributors channel on Telegram for support.

**Closed as completed** 2024-09-02 17:38 UTC
Labels: good first issue, ODHack7, design
